version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8501"
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword@db/chat_history
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chat_history
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

